apiVersion: v1
kind: Service
metadata:
  name: ${project_name}-frontend-service
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: NodePort
  selector:
    app: ${project_name}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: ${project_name}-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${project_name}-frontend
  template:
    metadata:
      labels:
        app: ${project_name}-frontend
    spec:
      containers:
        - name: ${project_name}-frontend
          image: ${frontend_image_url}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: API_URL
              value: ${backend_api_url}
      restartPolicy: Always
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${project_name}-frontend-ingress
spec:
  defaultBackend:
    service:
      name: ${project_name}-frontend
      port:
        number: 80