#variable "commit_hash" {
#  description = "Git commit hash"
#  type        = string
#}

variable "project_id" {
  type = string
}

variable "region" {
  type    = string
  default = "europe-north1"
}

variable "zone" {
  type    = string
  default = "europe-north1-a"
}

variable "k8s_backend_service_name" {
  type        = string
  description = "Name of the backend service autogenerated"
}

variable "db_password" {
  type = string
}

variable "domain" {
  type        = string
  description = "Domain name in form of example.com"
}